version: "2"
services:
  web:
    build: .
    ports:
      - "1337:1337"
    environment:
      NODE_ENV: dev
      DB_HOST: mongo
      DB_PORT: 27017
      DB_USER: WSDMLbD5gJYrECicOp2m
      DB_PASSWORD: SXZ7gLX4vNUgkHWcazZU
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: fgKLhwYg37XdgONJsGtN
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=WSDMLbD5gJYrECicOp2m
      - MONGO_INITDB_ROOT_PASSWORD=SXZ7gLX4vNUgkHWcazZU
  cache:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass fgKLhwYg37XdgONJsGtN